#!/bin/bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
original_dir="$( pwd )"
cd "$script_dir"


echo "#################################"
echo "### mishell by pkristian"
echo "### version 0.82"
echo "#################################"

profile_directory=
log_file=
#load config
. ./config.sh


profile_name=$1
profile_file="$profile_directory""$profile_name"'.sh'

current_user=`whoami`
echo "Profile:" $profile_name
echo "Current user:" $current_user


if [ ! -f $profile_file ]; then
	echo "ERROR: profile does not exist"
	echo "not found:" $profile_file
	exit
fi

#define variables
required_user=
repo_dir=
repo_remote=
repo_branch=

#load profile file
echo "Loading profile file:" $profile_file
. $profile_file

echo "> required_user = $required_user"
echo "> repo_dir      = $repo_dir"
echo "> repo_remote   = $repo_remote"
echo "> repo_branch   = $repo_branch"

#check right user

if [ "$current_user" != "$required_user" ]; then
	echo "ERROR: Mismatching user"
	echo "Required: " $required_user
	echo "Current:  " $current_user
	exit
fi

#changing directory
cd $repo_dir

#fetching
echo 'Fetching...'
if [ -z "$repo_remote" ]; then
	echo "local branch"
	branch="$repo_branch"
else
	git fetch "$repo_remote" "$repo_branch"
	branch=$repo_remote"/"$repo_branch
fi
echo "Branch: $branch"
#current commit
current_commit=`git rev-parse HEAD`
echo "Current commit: " "$current_commit"
#target commit
target_commit=`git show-ref $branch | awk '{print $1}'`
echo "Target commit:" "$target_commit"

if [ $current_commit == $target_commit ]; then
	echo ""
	echo "### SKIPPING ###"
else
	echo "Target branch: " $repo_branch

	##do stuff
	echo "# Executing beforeDeploy:"
	beforeDeploy

	echo "# Deploying..."
	git checkout -f "$target_commit"

	echo "# Executing afterDeploy:"
	afterDeploy

	cd "$script_dir"
	if [ ! -f "$log_file" ]; then
		echo "$log_file"
		touch "$log_file"
	fi
	now=`date +"%Y-%m-%d %H:%M:%S"`
	echo $now "Deployed "$profile_name$'\r' >> "$log_file"
	echo "### DONE ###"
fi
echo ""
cd "$original_dir"
return 0
